# Generated by Django 4.0.4 on 2022-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_accepted_book_appropriate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(default=4, upload_to='books/static'),
            preserve_default=False,
        ),
    ]
